<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDefaultItems>false</EnableDefaultItems>

    <PackageType>Template</PackageType>
    <PackageId>Avolutions.Baf.Templates</PackageId>
    <Version>0.2.0</Version>

    <Title>Avolutions BAF Templates</Title>
    <Company>Avolutions</Company>
    <Authors>Alexander Vogt</Authors>
    <Description>Project templates for creating new applications with Avolutions Business Application Framework (BAF).</Description>
    <RepositoryUrl>https://github.com/avolutions/baf-templates</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="" />
    <None Include="..\LICENSE" Pack="true" Visible="false" PackagePath="" />
    <None Include="baf-*/**/*"
          Pack="true"
          PackagePath="content/"
          Exclude="**/bin/**;**/obj/**;**/*.user;**/*.lock.json" />
  </ItemGroup>
</Project>
